### ISSUE TITLE
new feature: player routes

### ISSUE THREAD

**Issue by matt-yml** [matt-yml/pk#100]
pogo has introduced the new **routes** feature and people want to learn about it.

let's handle it from two ways:

- discord community
- map & scanning tech

https://leekduck.com/events/routes-new-feature/

![Image](https://github.com/matt-yml/pk/assets/41926716/876bc60a-4676-48a5-b258-da53c2bf9f9e)

**Comment by matt-yml** [comment]
- [ ] do we need to add a channel? 
- [ ] is there a new tool in pokenav for it? 
- [ ] will the map scanning handle any of this?

we need lots of help to get this interesting new feature going. 
all are welcome!
please create a github account to post here, or in discord [#ideas-and-questions](https://discord.com/channels/739865703561035778/879444347840499852)

**Comment by matt-yml** [comment]
@gigi asked about adding a channel
will keep in #general for now until it's a more regular thing.
[discord convo](https://discord.com/channels/739865703561035778/879444347840499852/1134117604139733112)

suggested a finger sketch screen shot for now.


![Image](https://github.com/matt-yml/pk/assets/41926716/09b0af5e-4fb8-4767-97a8-200e8046ebfd)

**Comment by matt-yml** [comment]
can we use dyno _tags_ or another dyno feature?

i'm already paying for dyno premium. may as well use it
https://docs.dyno.gg/en/modules/tags


[<img src="https://github.com/matt-yml/pk/assets/41926716/a78f7fe3-f0e5-4a28-86ad-0b9f4b5da149" alt="dyno tags" width="200"/>](https://www.youtube.com/watch?v=q0pOeLEM8Sg)

https://www.youtube.com/watch?v=q0pOeLEM8Sg

**Comment by matt-yml** [comment]
routes have been added (in theory) to the lowest layer MITM process. 
need back/front end support now


![Image](https://github.com/matt-yml/pk/assets/41926716/8f239186-6598-4e2e-acac-9162e8088c7d)

**Comment by matt-yml** [comment]
artwork is being added for routes on the map. 
this is a good sign somebody may write code for it. 



![Image](https://github.com/matt-yml/pk/assets/41926716/284b03d2-ec96-4945-bbb0-62b393eaf6f6)

**Comment by gigi** [comment]
@matt-yml 
It seems that I'm not the correct person for this)

**Comment by matt-yml** [comment]
Oh I thought you'd be good at the social half of routes.

You have early experience with making routes and could probably contribute
a lot.

**Comment by matt-yml** [comment]
may consider hybridized approach for route detection/reporting
have an idea, but need to keep this one under wraps bc it affects the bigger picture

**Comment by matt-yml** [comment]
implementing go based proto data processor:
https://github.com/matt-yml/gore/issues/476

**Comment by matt-yml** [comment]
working in dragol

![Image](https://github.com/matt-yml/pk/assets/41926716/aedd4f3f-87cc-47a7-b273-3f78f565d5ca)



![Image](https://github.com/matt-yml/pk/assets/41926716/e6d650dc-4637-4f79-acce-6e076e9f76ce)
