### ISSUE TITLE
Request for Hillsborough initial IV fence

### ISSUE THREAD

**Issue by matt-yml** [matt-yml/pk#70]
Soliciting suggestions for the main poke catching stretch. 
Please comment, suggest, or submit fences here with your Github account. 

An admin can also be @mentioned in the [#ideas-and-questions](https://discord.com/channels/739865703561035778/879444347840499852) channel

Premium post:
[<img src="https://user-images.githubusercontent.com/41926716/214997845-791f54bb-5c45-4957-ba55-e5ae66331253.png" alt="ask for fence" width="500"/>](https://discord.com/channels/739865703561035778/1066181399800991745/1068357561704788039)

Community post:
[<img src="https://user-images.githubusercontent.com/41926716/214998106-6d0f8244-fad5-49d3-b135-ada0c38f47f1.png" alt="ask for fence" width="500"/>](https://discord.com/channels/739865703561035778/1066175158349475862/1068358269954961429)

**Comment by matt-yml** [comment]
here's the initial hillsborough quick fence. 
@suzydog69 can you give it the charlotte north treatment? 
the sub fence doesn't need work, but the larger extents of official hillsborough do


![Image](https://github.com/matt-yml/pk/assets/41926716/fda7f310-32e2-4913-8ac3-626bcd4e6779)

**Comment by Suzydog69** [comment]
So you want me polygon interpretation on the blue Hillsborough shape? How many polygons you looking for? Ie how many shapes do you see making up the blue shape? 1? 2? 4?

**Comment by matt-yml** [comment]
Yes, polygon interpolation of blue.
Let's do one shape to start. 

I really eyeballed that one quickly so I don't expect yours to resemble it a lot. 
We can add an "outer Hillsborough" polygon afterwards if the official one is much smaller.

**Comment by Suzydog69** [comment]
Sounds good. Will do.

**Comment by Suzydog69** [comment]
Uploaded json for Hillsborough to you for review. Really hard to know what to include/what to exclude. Don't know Jack shit about the area.

**Comment by Suzydog69** [comment]
Tried to use spawn points. Exclude schools. Include parks, etc.

**Comment by matt-yml** [comment]
This is looking great. Let's include schools so the router will scan them if they ever get points in the future. 
Also, it's good that you extended the RDU boundaries. Those were done quickly and unintentionally may be leaving some people/locations out. 


![Image](https://github.com/matt-yml/pk/assets/41926716/3d5ce25c-7a7b-4dd3-8707-2f164c1d5c9a)

**Comment by matt-yml** [comment]
Need to trim this down for the IV portion. Will address in another issue.
