### ISSUE TITLE
Automate the joining process with a dyno form

### ISSUE THREAD

**Issue by matt-yml** [matt-yml/pk#87]
The onboard process we have now is fun, but it requires too much attention.
Users who leave and return can't see their prior posts, there's a security problem with public people reading who's joined the server in the past. 
For legal reasons also need an explicit acceptance of the T&C.

Implement a Dyno form and revamp the onboarding process.

- [x] Write Dyno form
- [x] Configure new roles and automation
- [x] Rewrite the #getting-started channel
- [x] Setup auto responses & write documentation to guide applicant through process
- [x] Setup alerts for map ops team
- [x] Rewrite the wiki to match
- [x] Update web GUI for new process
- [x] Test test test
- [x] Write instruction for map ops
- [ ] Third party test by admin besides @mattlesnake 
- [x] Live real user test.

**Comment by matt-yml** [comment]
![Image](https://user-images.githubusercontent.com/41926716/221285442-5cd01dfa-0468-4eaf-9e51-f5ead4c8d53d.png)



![Image](https://user-images.githubusercontent.com/41926716/221285992-d2c5689b-ea85-46f5-9c89-bdb9fd3d6f1a.png)



![Image](https://user-images.githubusercontent.com/41926716/221286016-fd59d2c7-afec-4eec-95c6-caa0c39e83e9.png)

**Comment by matt-yml** [comment]
Announced to #map-ops and mentioned to @turing tester.
Requested people help walk through and test it. 
https://discord.com/channels/739865703561035778/767782892663209984/1078770906492575805

Awaiting results.

Proposed process:
```
1. A new application appears in #member-applications . (I've set my notifications to "all")
2. Check the application and verify they accepted the Terms and Conditions and other stuff looks good.
3. Check to see they submitted a valid profile pic in #trainer-profiles . Copy and paste it into their thread in #member-applications .
4. Clean up the #welcome-messages channel (Leave the embeded example)
5. Grant them the `member` role & remove the `applicant` role.
(Keep the `touched` role)
6. DM or mention them in a channel like #general or #welcome-messages letting them know they're in. 
```

**Comment by matt-yml** [comment]
This is working live now. Skipping map-ops test request.
Save profile pic in thread.

Will add custom command to welcome the user and point to wiki & help channels.





![Image](https://user-images.githubusercontent.com/41926716/224125051-492f6249-4081-414e-ad90-36100e963b11.png)

**Comment by turing** [comment]
ohai
